# Generated by Django 6.0.2 on 2026-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
