# Generated by Django 6.0.2 on 2026-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
